version: "3.9"
services:
  dart-server:
    restart: always
    build: .
    ports:
      - 4000:8080
    volumes:
      - packages:/packages
    entrypoint: ["/app/bin/server.exe"]

volumes:
  packages:
  db_data:
