version: "3.9"
services:
  mongo:
    restart: always
    image: mongo
    volumes:
      - db_data:/data/db
  dart-server:
    restart: always
    build: .
    ports:
      - 4000:8080
    depends_on:
      - mongo
    volumes:
      - packages:/packages
    entrypoint: ["/app/bin/server.exe"]

volumes:
  packages:
  db_data:
